name: Test
on: [push, pull_request]

jobs:
  update:
    name: Test

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
